#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



name: Pull Request on Branch Push
on:
  pull_request:
    branches: [demo]
jobs:
  lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: checkout the code
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # BRANCH_PREFIX: "update/"
          # PULL_REQUEST_BRANCH: "master"