name: trivy
on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: "checkout source"
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        run: |
          docker buildx build -t my-app:latest .
        
      - name: run trivy
        uses: aquasecurity/trivy-action@0.21.0
        with:
          image-ref: 'my-app:latest'
          format: sarif
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: "Upload Trivy scan results to Github Security tab"
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
