name: trivy
on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: "checkout source"
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: roxy:latest
        
      - name: run trivy
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: roxy:latest
          format: serif
          output: 'trivy-results.serif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: "Upload Trivy scan results to Github Security tab"
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.serif'
