name: Pull Request on Branch Push
on:
  pull_request:
    branches: [demo]
jobs:
  lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: checkout the code
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          # BRANCH_PREFIX: "update/"
          # PULL_REQUEST_BRANCH: "master"