name: Analyse Dockerfile
on:
  push:
    
jobs:
  hadolint:
    name: hadolint scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
          format : sarif
          output-file: hadolint-results.sarif
        
      - name: debug the code part 1
        if: always()
        run: |
          pwd
          ls 


      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3 

        if: always()
        with:
          sarif_file: hadolint-results.sarif
            wait-for-processing: true

      - name: debug the code part 2
        run: |
          pwd
          ls 

    